services:
  zhimo:
    image: ghcr.io/srien11/muduo-http-ai-server-project:latest
    ports:
      - "8080:8080"
    volumes:
      - ./server.conf:/app/server.conf
      - ./memory:/app/memory
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
